### ISSUE TITLE
Can't deal with local source

### ISSUE THREAD

**Issue by FransUrbo** [patrickchugh/terravision#43]
I often use local paths while I'm developing my modules.

I have something like this:
```
module "mymodule" {
    source = "/home/turbo/src/module
    [...]
}
```

**Comment by ddproxy** [comment]
A relative path seems to work properly however,

```
module "mymodule" {
  source = "../modules/mymodule"
}
```

**Comment by patrickchugh** [comment]
Hardcoding a specific path on your local machine will mean your code is not portable to another user, but good catch nonetheless

**Comment by FransUrbo** [comment]
I know, that's not the point (of it being used anywhere else). I only do it when I have multiple layers of modules, and I'm working on one (or more) "down the tree"..

I always change it back to a Git source address before commiting.

**Comment by patrickchugh** [comment]
@FransUrbo This has now been fixed with the latest push. Please check.
