### ISSUE TITLE
Unable to clone versioned modules

### ISSUE THREAD

**Issue by bengels00** [patrickchugh/terravision#51]
When trying to clone https://module?ref=foo, terravision errors while cloning without appending _?ref=foo_ to the URL works.
Example:

```
Loading Sources..
  Downloading External Module: git::https://git-codecommit.eu-central-1.amazonaws.com/v1/repos/terraform-module-cloudwatch-sharing?ref=1.0
    Cloning from Terraform registry source: https://git-codecommit.eu-central-1.amazonaws.com/v1/repos/terraform-module-cloudwatch-sharing?ref=1.0
0it [00:00, ?it/s]
ERROR: Unable to call Git to clone repository! Check git and SSH fingerprints and keys are correct and ensure the URL https://git-codecommit.eu-central-1.amazonaws.com/v1/repos/terraform-module-cloudwatch-sharing?ref=1.0 is reachable via CLI.

```

**Comment by patrickchugh** [comment]
Thanks this will be fixed soon

**Comment by patrickchugh** [comment]
@bengels00 Can you git pull the latest code and try again with my latest fix?

**Comment by bengels00** [comment]
@patrickchugh Getting our modules with ?ref=xyz suffix works now, nice! But now I'm stumbling over the following issue:

```
[...]
Loading Sources..
  Downloading External Module: github.com/terraform-aws-modules/terraform-aws-vpc?ref=v3.2.0
    Assuming Terraform Enterprise API Server URL: https://github.com/api/registry/v1/modules/

ERROR: No TFE_TOKEN environment variable set. Unable to authorise with Terraform Enterprise Server
```

(We don't use terraform enterprise at all.)

**Comment by patrickchugh** [comment]
Updated the code, can you try again?

**Comment by patrickchugh** [comment]
@bengels00 The issue was the missing "http" prefix

**Comment by bengels00** [comment]
@patrickchugh well, module downloading went like a charm, now.
Unfortunately the python process is taking ~100% CPU since more than 20 minutes and has not come to some result

```
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                                                                  
  56324 bj        20   0  500240  54488  14848 R  99.7   0.3  22:44.57 python                       
```

**Comment by bengels00** [comment]
Module downloading is fixed.

**Comment by patrickchugh** [comment]
It's probably an infinite loop and the logic interpreter has hung. If you can share the Terraform files you are using I can try to fix it ?

**Comment by patrickchugh** [comment]
@bengels00 you can remove any sensitive data if needed or just share the source for the last module it hung on

**Comment by bengels00** [comment]
@patrickchugh  I'd love helping to dig deeper into this, but the tf code is ~6k lines, ~250 resources, multiple times calling sub-modules, with resource names and filenames pointing to the name of our customer, the software they're using etc.
I can't even exactly identify in which module it's hanging. terravision is processing ```aws_ecs_service._``` but that's a resource being created in 6 different module invocations and I don't see which invocation is the affected one. If I'd knew which one it is, I'd clean up the relevant terraform parts from customer references/sensitive data and supply them.

**Comment by patrickchugh** [comment]
@bengels00 let me work on a fix that tells you the offending line and resources. Will get back to you soon
