### ISSUE TITLE
pip   ERROR: kdave 0.2.2 has requirement Click==8.0, but you'll have click 8.1.3 which is incompatible

### ISSUE THREAD

**Issue by ViktorUJ** [patrickchugh/terravision#58]
ERROR: kdave 0.2.2 has requirement Click==8.0, but you'll have click 8.1.3 which is incompatible.
Installing collected packages: click
  Attempting uninstall: click
    Found existing installation: click 8.0.0
    Uninstalling click-8.0.0:
      Successfully uninstalled click-8.0.0
Successfully installed click-8.1.3
--------
I think need   update   requirements.txt
set version **click==8.0**

**Comment by patrickchugh** [comment]
Thanks please raise a PR if you can.

**Comment by patrickchugh** [comment]
Closing since this can be resolved by using poetry and VirtualEnvs in python
