### ISSUE TITLE
Could you please add a license file?

### ISSUE THREAD

**Issue by johanneskastl** [patrickchugh/terravision#63]
I have not found any hints on licensing for terravision. Could you please add a License (bonus points if it is in away that GitHub shows it on the right hand side).

Thanks!

**Comment by maker2413** [comment]
A License would be very useful to other users that want to contribute to the project.

**Comment by guipaivanz** [comment]
+1

**Comment by patrickchugh** [comment]
Done as requested. Added MPL license

**Comment by patrickchugh** [comment]
@guipaivanz @johanneskastl @maker2413  Thanks for your patience
