### ISSUE TITLE
Unhandled error: <class 'IndexError'>, list index out of range, <traceback object at 0x7f61b0042b40>

### ISSUE THREAD

**Issue by aomarabdelaziz** [patrickchugh/terravision#81]
while using this command terravision draw --source https://github.com/aomarabdelaziz/devops-ejs-express-api-hub//Terraform --show
I got this error

Plan: 52 to add, 0 to change, 0 to destroy.

──────────────────────────────────────────────────────────────────────────────────────────────────────────

Saved the plan to: tfplan.bin

To perform exactly these actions, run the following command to apply:
    terraform apply "tfplan.bin"

Analysing plan..

Unhandled error: <class 'IndexError'>, list index out of range, <traceback object at 0x7f61b0042b40>

**Comment by patrickchugh** [comment]
@aomarabdelaziz an you try to do a git pull with the latest code and see if this is fixed? If not please supply some sample source so I can try to reproduce the error. Thanks!

**Comment by aomarabdelaziz** [comment]
./terravision draw --source https://github.com/aomarabdelaziz/devops-ejs-express-api-hub//Terraform --show
Traceback (most recent call last):
  File "/home/abdelaziz-omar/terravision/resource_classes/aws/groups.py", line 10, in <module>
    base_path = sys._MEIPASS
AttributeError: module 'sys' has no attribute '_MEIPASS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abdelaziz-omar/terravision/./terravision", line 7, in <module>
    import modules.drawing as drawing
  File "/home/abdelaziz-omar/terravision/modules/drawing.py", line 26, in <module>
    from resource_classes.aws.groups import *
  File "/home/abdelaziz-omar/terravision/resource_classes/aws/groups.py", line 13, in <module>
    base_path = os.path.dirname(shutil.which("terravision")) or os.path.dirname(
  File "/usr/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType


I don't know why i got this error

- Python 3.10.12
- pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

**Comment by aomarabdelaziz** [comment]
> @aomarabdelaziz can you try to do a git pull with the latest code and see if this is fixed? I managed to run it with your source link on my machine now

it works now fine , thanks
