### ISSUE TITLE
Unhandled error: <class 'TypeError'>, unsupported operand type(s) for +: 'bool' and 'str', <traceback object at 0x1065cab40>

### ISSUE THREAD

**Issue by thiagoalexandria** [patrickchugh/terravision#82]
## Problem Description
When running the terravision draw command in a local directory containing Terraform code, an unhandled error is triggered:

`Unhandled error: <class 'TypeError'>, unsupported operand type(s) for +: 'bool' and 'str', <traceback object at 0x1065cab40>
`

## Context
Command Executed: terravision draw
Environment: Python 3.9.6
Terravision Version: 0.5
Terraform Version: v1.4.6

## Steps to Reproduce
Access the directory with the Terraform code.
Run the terravision draw command.
Observe the mentioned error.

## Expected Behavior
The terravision draw command was expected to execute correctly without generating errors related to unsupported operand types between data types.

## Additional Notes
```
Unprocessed terraform graph dictionary:

{
    "aws_instance.webserver": [
        "aws_lb_target_group_attachment.name"
    ],
    "aws_lb.nginx": [
        "aws_lb_listener.name"
    ],
    "aws_lb_listener.name": [],
    "aws_lb_target_group.nginx": [
        "aws_lb_listener.name",
        "aws_lb_target_group_attachment.name"
    ],
    "aws_lb_target_group_attachment.name": [],
    "aws_security_group.allow_http": [
        "aws_instance.webserver",
        "aws_lb.nginx"
    ]
}

Parsing Terraform Source Files..
  Added Source Location: .
  Parsing ./data.tf
    Found 3 data stanza(s)
  Parsing ./main.tf
    Found 2 module stanza(s)
  Added Source Location: /Users/thiagoalexandria/Documents/Projetos/Terraform/aws_tf_estudos/modules/two-tier
  Added Source Location: /Users/thiagoalexandria/Documents/Projetos/Terraform/aws_tf_estudos/modules/two-tier
  Parsing ./variables.tf
  Parsing /Users/thiagoalexandria/Documents/Projetos/Terraform/aws_tf_estudos/modules/two-tier/output.tf
  Parsing /Users/thiagoalexandria/Documents/Projetos/Terraform/aws_tf_estudos/modules/two-tier/ec2.tf
    Found 2 resource stanza(s)
  Parsing /Users/thiagoalexandria/Documents/Projetos/Terraform/aws_tf_estudos/modules/two-tier/variables.tf
    Found 8 variable stanza(s)
  Parsing /Users/thiagoalexandria/Documents/Projetos/Terraform/aws_tf_estudos/modules/two-tier/alb.tf
    Found 4 resource stanza(s)

Processing variables..

Processing resources..

Checking for additional links between 6 resources..

Conditional resource list:
Unhandled error: <class 'TypeError'>, unsupported operand type(s) for +: 'bool' and 'str', <traceback object at 0x1065cab40>
```

**Comment by patrickchugh** [comment]
@rodrigo-segui @thiagoalexandria  Can you try to do a git pull with the latest code and see if this is fixed? If not please supply some sample source so I can try to reproduce the error. Thanks!

**Comment by thiagoalexandria** [comment]
I'm facing the same error; it generates the plan, reads it, but when it reaches the Conditional resource list stage, it fails with an error indicated in the issue:

```
Unhandled error: <class 'TypeError'>, unsupported operand type(s) for +: 'bool' and 'str', <traceback object at 0x108641880>
```

Here's the link to the repository with the code I'm testing.

https://github.com/thiagoalexandria/terravision-example

**Comment by patrickchugh** [comment]
@thiagoalexandria I think there is some error in the TF code. When I try to draw your github link I get 
`Generating Terraform Plan..

data.aws_ami.amazon_linux: Reading...
data.aws_subnet.pub1: Reading...
data.aws_subnet.pub2: Reading...
data.aws_ami.amazon_linux: Read complete after 2s [id=ami-025a07aa284285222]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: no matching EC2 Subnet found
│ 
│   with data.aws_subnet.pub1,
│   on data.tf line 1, in data "aws_subnet" "pub1":
│    1: data "aws_subnet" "pub1" {
│ 
╵
╷
│ Error: no matching EC2 Subnet found
│ 
│   with data.aws_subnet.pub2,
│   on data.tf line 7, in data "aws_subnet" "pub2":
│    7: data "aws_subnet" "pub2" {
│ 
╵`

**Comment by patrickchugh** [comment]
Once there are no TF errors, I can try again

**Comment by thiagoalexandria** [comment]
Now it works, thanks a lot !
