### ISSUE TITLE
terravision is destroying the configured backend

### ISSUE THREAD

**Issue by martinscholz-mediatis** [patrickchugh/terravision#84]
Hi,

When I try to run the latest release, since the switch to binary version, terravision always tempers with my backend setup and removes the configuration from the directory, so that an access to the gitlab stored state is no longer beeing reached cause it needs a login, resetup this and try terravision again, fails again, this is atm annoying.

**Comment by patrickchugh** [comment]
I am starting a new branch to fix this - can you try with the code in the bugfix-tfdirectory branch? @martinscholz-mediatis

**Comment by patrickchugh** [comment]
Didn't hear back so assuming fixed
