### ISSUE TITLE
Please supply a way to pass through terraform init args

### ISSUE THREAD

**Issue by dnk8n** [patrickchugh/terravision#85]
For example, for projects that abstract secrets from the remote state config we init like this:

`terraform init -backend-config=backend.tfconf`

From what I can gather, terravision only supports `terraform init` (no args)

**Comment by dnk8n** [comment]
Note, how corresponding templates look in this case:

``` main.tf
terraform {
  backend "s3" {}
}
```

``` backend.tfconf
region = "af-south-1"
bucket = "terraform-state"
key    = "terraform.tfstate"
```

**Comment by patrickchugh** [comment]
Didn't hear back so closing
